
spring:
  datasource:
    #       使用阿里巴巴的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1forlove
#    似乎是最快的连接池。。
    hikari:
#      自定义连接池名字
      pool-name: DateHikariCP
#      最小空闲连接数
      minimum-idle: 5
      #空闲连接存货最大时间，默认一小时。自定义半小时
      idle-timeout: 1800000
#      最大连接池数
      maximum-pool-size: 10
#      从连接池返回的连接自动提交
      auto-commit: true
#      最大存活时间
      max-lifetime: 1800000
#      连接超时时间 30秒
      connection-timeout: 30000
#      测试连接是否可用的查询语句（心跳机制）
      connection-test-query: SELECT 1
  redis:
    host: 8.131.58.206
    port: 6379
    database: 0
    password: redisPassword1234




#    mybatis-plus配置
mybatis:
#  配置mapper.xml映射文件 classpath 包含resources包
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  配置mybatis数据返回类型别名路径(默认是类名)
  type-aliases-package: com.anrolsp.seckill.pojo

#Mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    # 把对应包下面的class的日志文件设置为debug级别
#    com.anrolsp.seckill.mapper: debug
    com.anrolsp.seckill.dao: debug
server:
  port: 8989

